language: node_js
node_js:
  - "8.11.4"
cache:
  directories:
    - "node_modules"
script: 
  - if [ $TRAVIS_BRANCH = 'dev' ]; npm run check-travis; fi
  - if [ $TRAVIS_BRANCH = 'master' ]; npm run lint; fi
